export const FIGHT_CONSTANTS = {
    TILE_WIDTH: 48,
    TILE_HEIGHT: 48,
    CAN_HAVE_TRASH_TILES: false,
    CAN_HAVE_LYING_TILES: false,
    CAN_HAVE_MULTI_BOMB_TILES: false,
    CAN_HAVE_TENTACLES: false,
    BOMB_COUNTER_CAN_LIE: false,
    EMERGENCY_GENERATOR_CUTOFF_NUMBER: 100000,
    TENTACLE_INCREMENT: 18,
};

export const ADVANCED_MECHANICS = {
    FIGHT_CAN_HAVE_TRASH_TILES: "fightCanHaveTrashTiles",
    FIGHT_CAN_HAVE_LYING_TILES: "fightCanHaveLyingTiles",
    FIGHT_CAN_HAVE_MULTI_BOMB_TILES: "fightCanHaveMultiBombTiles",
    FIGHT_CAN_HAVE_TENTACLES: "fightCanHaveTentacles",
    BOMB_COUNTER_CAN_LIE: "bombCounterCanLie",
};

export const FIGHT_INPUT_TYPES = {
    REVEAL: "REVEAL",
    FLAG: "FLAG",
    QUERY: "QUERY",
    REMOVE_TRASH: "REMOVE_TRASH",
    REMOVE_BOMB: "REMOVE_BOMB",
    REMOVE_LIES: "REMOVE_LIES",
    UMBRELLA: "UMBRELLA",
    TOWER: "TOWER",
    BLOCK: "BLOCK",
};
