export const PLAYER_EVENTS = {
    LOSE_HP: 'LOSE_HP',
    GAIN_HP: 'GAIN_HP',
    LOSE_GOLD: 'LOSE_GOLD',
    GAIN_GOLD: 'GAIN_GOLD',
    GAIN_UPGRADE: 'GAIN_UPGRADE',
    LOSE_UPGRADE: 'LOSE_UPGRADE',
}

export const UI_EVENTS = {
    UPDATE_GOLD: 'UPDATE_GOLD',
    UPDATE_HEALTH: 'UPDATE_HEALTH',
    UPDATE_HEALTH_MAX: 'UPDATE_HEALTH_MAX',
    DISPLAY_MESSAGE:'DISPLAY_MESSAGE',
    UPDATE_UPGRADES: 'UPDATE_UPGRADES'
}