export const FIGHT_CONSTANTS = {
    TILE_WIDTH: 36,
    TILE_HEIGHT: 36,
    CAN_HAVE_TRASH_TILES: false,
    CAN_HAVE_LYING_TILES: false,
    CAN_HAVE_MULTI_BOMB_TILES: true,
    EMERGENCY_GENERATOR_CUTOFF_NUMBER: 100000,
};

export const FIGHT_INPUT_TYPES = {
    REVEAL: "REVEAL",
    FLAG: "FLAG",
    QUERY: "QUERY",
    REMOVE_TRASH: "REMOVE_TRASH",
    REMOVE_BOMB: "REMOVE_BOMB",
    REMOVE_LIES: "REMOVE_LIES",
};
