import { FIGHT_INPUT_TYPES } from "@/game/types/fightConstants";

export const GAME_CONSTANTS = {
    startingHp: 5,
    startingMaxHp: 5,
    startingGold: 5,
    startingLevel: 1,
    startingBombIntensity: 2,
    startingLuck: 0,
    startingName: "Jan Eator",
    startingBombNum: 4,
    startingFightGridWidth: 8,
    startingFightGridHeight: 8,
    startingOverworldGridWidth: 5,
    startingOverworldGridHeight: 5,
    startingOverworldShops: 2,
    startingOverworldFights: 5,
    startingOverworldBuffs: 2,
    startingOverworldTraps: 2,
    startingShopGridWidth: 3,
    startingShopGridHeight: 4,
    startingShopItemNumber: 5,
    startingFightGoldReward: 5,
    endLevel: 8,
    startingFightInputTypes: [
        FIGHT_INPUT_TYPES.REVEAL,
        FIGHT_INPUT_TYPES.FLAG,
        FIGHT_INPUT_TYPES.QUERY,
        // FIGHT_INPUT_TYPES.REMOVE_TRASH,
        // FIGHT_INPUT_TYPES.REMOVE_BOMB,
        // FIGHT_INPUT_TYPES.REMOVE_LIES,
    ],
    startingRemoveTrashNum: 1,
    startingRemoveBombNum: 10,
    startingRemoveLyingNum: 1,
    startingTrashTileNum: 2,
    startingLyingTileNum: 1,
};

export const NAME_CHOICES = [
    "Jan Eator",
    "Cousteau Dian",
    "Han Demon",
    "May Tenance",
    "Dustin Buster",
];
