export const GAME_CONSTANTS = {
    startingHp: 50,
    startingMaxHp: 50,
    startingGold: 50,
    startingLevel: 1,
    startingBombIntensity: 3,
    startingName: "Jan Eator",
    startingBombNum: 4,
    startingFightGridWidth: 8,
    startingFightGridHeight: 8,
    startingOverworldGridWidth: 5,
    startingOverworldGridHeight: 5,
    startingOverworldShops: 2,
    startingOverworldFights: 5,
    startingOverworldBuffs: 2,
    startingOverworldTraps: 2,
    startingShopGridWidth: 3,
    startingShopGridHeight: 4,
    endLevel: 8,
}