export const SCENES = {
    Boot: "Boot",
    Preloader: "Preloader",
    MainMenu: "MainMenu",
    Overworld: "Overworld",
    MainGame: "MainGame",
    GameOver: "GameOver",
    Fight: "Fight",
    Hud: "Hud",
    Shop: "Shop",
    NewGame: "NewGame",
    BossFight: "BossFight",
    GameWon: "Game Won",
    TrapOverlay: "TrapOverlay",
    HallOfFame: "HallOfFame",
};
