import { GAME_CONSTANTS } from "@/game/GameState/gameConstants";
import { flavorConstants } from "@/game/constants/flavorConstants";

export const SHOP_ITEMS: { [key: string]: shopItemType } = {
    HEAL_FULL: {
        id: "HEAL_FULL",
        name: "Thanksgiving Dinner",
        description: "Heals to full life",
        cost: 11,
        effect: { heal: 1000 },
        icon: 11,
        permanent: false,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    HEAL_TWO: {
        id: "HEAL_TWO",
        name: "2 Potato Chips",
        description: "Heal 2 life",
        cost: 2,
        effect: { heal: 2 },
        icon: 30,
        permanent: false,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    HEAL_EQUAL_TO_HP: {
        id: "HEAL_EQUAL_TO_HP",
        name: "Many Potato Chips",
        description: "Heals equal to Current HP",
        cost: 2,
        effect: { healEqualToHp: 1 },
        icon: 24,
        permanent: false,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    MOVE_BOMB_ONE: {
        id: "MOVE_BOMB_ONE",
        name: "Scary Face",
        description:
            "The first time you reveal a monster, it runs to a different spot",
        cost: 6,
        effect: { bombMove: 1 },
        icon: 6,
        permanent: true,
        singleton: false,
        activated: true,
        hasBeenUsed: false,
        restrictions: {},
    },
    MAX_HP_TWO: {
        id: "MAX_HP_TWO",
        name: "Hearty Snackbar",
        description: "Adds 2 life and max life",
        cost: 4,
        effect: { maxHp: 2 },
        icon: 9,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    MAX_HP_DOUBLE: {
        id: "MAX_HP_DOUBLE",
        name: "Pretzels",
        description: "Doubles Max Life only",
        cost: 9,
        effect: { maxHpDouble: 1 },
        icon: 32,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    MAX_HP_PERCENT_TWENTY: {
        id: "MAX_HP_PERCENT_TWENTY",
        name: "Pizza",
        description: "Adds 20% Max Hp, rounded up",
        cost: 5,
        effect: { maxHpPercent: 20 },
        icon: 29,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    REDUCE_DAMAGE_ONE: {
        id: "REDUCE_DAMAGE_ONE",
        name: "Gloves",
        description: "Reduces damage by 1",
        cost: 11,
        effect: { damage_reduce: 1 },
        icon: 13,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    REDUCE_DAMAGE_TWO: {
        id: "REDUCE_DAMAGE_TWO",
        name: "Armor",
        description: "Reduces damage by 2",
        cost: 25,
        effect: { damage_reduce: 2 },
        icon: 31,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    GRID_EXPAND_ONE: {
        id: "GRID_EXPAND_ONE",
        name: "Wrench",
        description: "Expand Office grids by 1 height and width",
        cost: 7,
        effect: { fightGridExpand: 1 },
        icon: 26,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    BOMB_NUMBER_REDUCE_FIVE: {
        id: "BOMB_NUMBER_REDUCE_FIVE",
        name: "Water",
        description: `Each ${flavorConstants.FIGHT_NAME} has 5 fewer ${flavorConstants.ENEMY_NAME_PLURAL}`,
        cost: 11,
        effect: { bombNumberReduce: 5 },
        icon: 27,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    FIGHT_GOLD_INCREASE_FIVE: {
        id: "FIGHT_GOLD_INCREASE_FIVE",
        name: "Promotion",
        description: `Gain 5 more gold for cleaned ${flavorConstants.FIGHT_NAME_PLURAL}`,
        cost: 13,
        effect: { fightGoldIncrease: 5 },
        icon: 19,
        permanent: true,
        singleton: true,
        activated: false,
        restrictions: {},
    },
    // REMOVE_TRASH_TILE_TWO: {
    //     id: "REMOVE_TRASH_TILE_TWO",
    //     name: "Big Trash Can",
    //     description: "Adds 2 uses to Remove Trash Tile",
    //     cost: 9,
    //     effect: { trashTileRemove: 2 },
    //     icon: "🥫",
    //     permanent: true,
    //     singleton: false,
    // },
    LUCK_IMPROVE_15: {
        id: "LUCK_IMPROVE_15",
        name: "Lucky Underpants",
        description: "You are a little Luckier",
        cost: 10,
        effect: { luckAdd: 15 },
        icon: 25,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    SHOP_ITEMS_ADD_3: {
        id: "SHOP_ITEMS_ADD_3",
        name: "Bigger Vending Machine",
        description: "Adds 3 more items to future vending machines",
        cost: 4,
        effect: { shopItemsAdd: 3 },
        icon: 16,
        permanent: true,
        singleton: true,
        activated: false,
        restrictions: {},
    },
    FLAWLESS_VICTORY_DOUBLE: {
        id: "FLAWLESS_VICTORY_DOUBLE",
        name: "Flawless Victory Mastery",
        description: "Doubles reward for flawless victories",
        cost: 7,
        effect: { flawlessVictoryDouble: 1 },
        icon: 17,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    BROOMTAR: {
        id: "BROOMTAR",
        name: "Broomtar",
        description: "The 12th time you chord in an office, gain $3",
        cost: 7,
        effect: {},
        icon: 3,
        permanent: true,
        singleton: false,
        activated: true,
        restrictions: {},
    },
    HARBROOM: {
        id: "HARBROOM",
        name: "Harbroom",
        description: "The 8th time you chord in an office, gain 2 life",
        cost: 8,
        effect: {},
        icon: 41,
        permanent: true,
        singleton: false,
        activated: true,
        restrictions: {},
    },
    INITIAL_CLICK_EXPAND_ONE: {
        id: "INITIAL_CLICK_EXPAND_ONE",
        name: "First Sweep Expander",
        description: "Enlarges your first sweep size by one",
        cost: 13,
        effect: { initialClickEnlarge: 1 },
        icon: 15,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    GRID_SHRINK_ONE: {
        id: "GRID_SHRINK_ONE",
        name: "Paint the Walls",
        description: "Shrink Office grids by 1 height and width",
        cost: 0,
        effect: { fightGridExpand: -1 },
        icon: 28,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    OVERWORLD_MAP_REVEAL: {
        id: "OVERWORLD_MAP_REVEAL",
        name: "Lobby Maps",
        description: "Reveals entire Lobby Map",
        cost: 7,
        effect: {},
        icon: 35,
        permanent: true,
        singleton: true,
        activated: false,
        restrictions: {},
    },
};

export const SPECIAL_ITEMS: { [key: string]: shopItemType } = {
    NEST_EGG: {
        id: "NEST_EGG",
        name: "Nest Egg",
        description: "Open to gain random items. ",
        cost: 0,
        effect: { nest_egg: 1 },
        icon: 11,
        permanent: true,
        singleton: true,
        activated: false,
        restrictions: { character: "CHAR_TWO" },
    },
};

// export const testingItems: shopItemType[] = [
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
// ];

export type shopItemType = {
    id: string;
    name: string;
    description: string;
    permanent: boolean;
    singleton: boolean;
    cost: number;
    effect: any;
    icon: number;
    activated: boolean;
    hasBeenUsed?: boolean;
    restrictions?: any;
};

export const SHOP_CONSTANTS = {
    SHOP_TILE_WIDTH: 192,
    SHOP_TILE_HEIGHT: 154,
    SHOP_TILE_OFFSET_X: 64,
    SHOP_TILE_NAME_OFFSET_Y: 0,
    SHOP_TILE_COST_OFFSET_Y: 24,
    SHOP_TILE_DESC_OFFSET_Y: 24,
    SHOP_TILE_FONT_SIZE: 32,
    NUM_PAD_TILE_WIDTH: 68,
    NUM_PAD_TILE_HEIGHT: 68,
};
