import { GAME_CONSTANTS } from "@/game/GameState/gameConstants";
import { flavorConstants } from "@/game/constants/flavorConstants";

export const SHOP_ITEMS: { [key: string]: shopItemType } = {
    HEAL_FULL: {
        id: "HEAL_FULL",
        name: "Thanksgiving Dinner",
        description: "Heals to full life",
        cost: 18,
        effect: { heal: 10000 },
        icon: 11,
        permanent: false,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    HEAL_TWO: {
        id: "HEAL_TWO",
        name: "2 Potato Chips",
        description: "Heal 2 life",
        cost: 2,
        effect: { heal: 2 },
        icon: 30,
        permanent: false,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    HEAL_EQUAL_TO_HP: {
        id: "HEAL_EQUAL_TO_HP",
        name: "Many Potato Chips",
        description: "Heals equal to Current HP",
        cost: 2,
        effect: { healEqualToHp: 1 },
        icon: 24,
        permanent: false,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    MOVE_BOMB_ONE: {
        id: "MOVE_BOMB_ONE",
        name: "Scary Face",
        description: `The first time you reveal a ${flavorConstants.ENEMY_NAME}, it runs to a different spot`,
        cost: 12,
        effect: { bombMove: 1 },
        icon: 6,
        permanent: true,
        singleton: false,
        activated: true,
        hasBeenUsed: false,
        restrictions: {},
    },
    REMOVE_BOMB_ONE: {
        id: "REMOVE_BOMB_ONE",
        name: "Dust Carrot",
        description: `The first time you reveal a ${flavorConstants.ENEMY_NAME}, you befriend it, and it leaves`,
        cost: 17,
        effect: { bombRemove: 1 },
        icon: 47,
        permanent: true,
        singleton: false,
        activated: true,
        hasBeenUsed: false,
        restrictions: {},
    },
    MAX_HP_TWO: {
        id: "MAX_HP_TWO",
        name: "Hearty Snackbar",
        description: "Adds 2 life and max life",
        cost: 4,
        effect: { maxHp: 2 },
        icon: 9,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    MAX_HP_DOUBLE: {
        id: "MAX_HP_DOUBLE",
        name: "Pretzels",
        description: "Doubles Max Life only",
        cost: 9,
        effect: { maxHpDouble: 1 },
        icon: 32,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    MAX_HP_PERCENT_TWENTY: {
        id: "MAX_HP_PERCENT_TWENTY",
        name: "Pizza",
        description: "Adds 20% Max Hp, rounded up",
        cost: 5,
        effect: { maxHpPercent: 20 },
        icon: 29,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    REDUCE_DAMAGE_ONE: {
        id: "REDUCE_DAMAGE_ONE",
        name: "Gloves",
        description: "Reduces damage by 1",
        cost: 12,
        effect: { damage_reduce: 1 },
        icon: 13,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    REDUCE_DAMAGE_TWO: {
        id: "REDUCE_DAMAGE_TWO",
        name: "Jumpsuit",
        description: "Reduces damage by 2",
        cost: 25,
        effect: { damage_reduce: 2 },
        icon: 31,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: { level: 2 },
    },
    GRID_EXPAND_ONE: {
        id: "GRID_EXPAND_ONE",
        name: "Wrench",
        description: "Expand Office grids by 1 height and width",
        cost: 7,
        effect: { fightGridExpand: 1 },
        icon: 26,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    BOSS_GRID_EXPAND_THREE: {
        id: "BOSS_GRID_EXPAND_THREE",
        name: "Boss's Wrench",
        description: "Expands Boss's Office grids by 2 height and width",
        cost: 7,
        effect: { bossFightGridExpand: 2 },
        icon: 37,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    BOMB_NUMBER_REDUCE_FIVE: {
        id: "BOMB_NUMBER_REDUCE_FIVE",
        name: "Water",
        description: `Each ${flavorConstants.FIGHT_NAME} has 5 fewer ${flavorConstants.ENEMY_NAME_PLURAL}`,
        cost: 11,
        effect: { bombNumberReduce: 5 },
        icon: 27,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    // REMOVE_BOMBS_BY_LUCK: {
    //     id: "REMOVE_BOMBS_BY_LUCK",
    //     name: "Lucky Duster",
    //     description: `Each ${flavorConstants.FIGHT_NAME} removes ${flavorConstants.ENEMY_NAME_PLURAL} based on luck`,
    //     cost: 11,
    //     effect: { bombNumberReduceByLuck: 5 },
    //     icon: 40,
    //     permanent: true,
    //     singleton: true,
    //     activated: false,
    //     restrictions: {},
    // },
    // REMOVE_TRASH_BY_LUCK: {
    //     id: "REMOVE_TRASH_BY_LUCK",
    //     name: "Lucky Bin",
    //     description: `Each ${flavorConstants.FIGHT_NAME} removes Trash spots based on luck`,
    //     cost: 11,
    //     effect: { trashNumberReduceByLuck: 5 },
    //     icon: 40,
    //     permanent: true,
    //     singleton: true,
    //     activated: false,
    //     restrictions: { advancedMechanics: "fightCanHaveTrashTiles" },
    // },
    // REMOVE_LIES_BY_LUCK: {
    //     id: "REMOVE_LIES_BY_LUCK",
    //     name: "Lucky Microscope",
    //     description: `Each ${flavorConstants.FIGHT_NAME} removes Lying Numbers based on luck`,
    //     cost: 11,
    //     effect: { lyingNumberReduceByLuck: 5 },
    //     icon: 40,
    //     permanent: true,
    //     singleton: true,
    //     activated: false,
    //     restrictions: { advancedMechanics: "fightCanHaveLyingTiles" },
    // },
    // REMOVE_TENTACLES_BY_LUCK: {
    //     id: "REMOVE_TENTACLES_BY_LUCK",
    //     name: "Lucky Tentacle Spray",
    //     description: `Each ${flavorConstants.FIGHT_NAME} removes Tentacles based on luck`,
    //     cost: 17,
    //     effect: { tentacleNumberReduceByLuck: 5 },
    //     icon: 40,
    //     permanent: true,
    //     singleton: true,
    //     activated: false,
    //     restrictions: { advancedMechanics: "fightCanHaveTentacles" },
    // },
    FIGHT_GOLD_INCREASE_FIVE: {
        id: "FIGHT_GOLD_INCREASE_FIVE",
        name: "Promotion",
        description: `Gain 3 more gold for cleaned ${flavorConstants.FIGHT_NAME_PLURAL}`,
        cost: 13,
        effect: { fightGoldIncrease: 3 },
        icon: 19,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    LUCK_IMPROVE_15: {
        id: "LUCK_IMPROVE_15",
        name: "Lucky Underpants",
        description: "You are a little Luckier",
        cost: 10,
        effect: { luckAdd: 35 },
        icon: 25,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    SHOP_ITEMS_ADD_3: {
        id: "SHOP_ITEMS_ADD_3",
        name: "Bigger Vending Machine",
        description: "Adds 3 more items to future vending machines",
        cost: 4,
        effect: { shopItemsAdd: 3 },
        icon: 16,
        permanent: true,
        singleton: true,
        activated: false,
        restrictions: {},
    },
    SHOP_ITEMS_ADD_3_AGAIN: {
        id: "SHOP_ITEMS_ADD_3_AGAIN",
        name: "Biggest Vending Machine",
        description: "Completely fills vending machines",
        cost: 7,
        effect: { shopItemsAdd: 3 },
        icon: 50,
        permanent: true,
        singleton: true,
        activated: false,
        restrictions: {
            item: "SHOP_ITEMS_ADD_3",
        },
    },
    FLAWLESS_VICTORY_DOUBLE: {
        id: "FLAWLESS_VICTORY_DOUBLE",
        name: "Flawless Victory Mastery",
        description: "Doubles reward for flawless victories",
        cost: 7,
        effect: { flawlessVictoryDouble: 1 },
        icon: 17,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    BROOMTAR: {
        id: "BROOMTAR",
        name: "Broomtar",
        description: "The 12th time you chord in an office, gain $3",
        cost: 7,
        effect: { activatedGainGold: 3 },
        icon: 3,
        permanent: true,
        singleton: false,
        activated: true,
        restrictions: {},
    },
    HARBROOM: {
        id: "HARBROOM",
        name: "Harbroom",
        description: "The 8th time you chord in an office, gain 2 life",
        cost: 8,
        effect: { activatedGainHp: 2 },
        icon: 41,
        permanent: true,
        singleton: false,
        activated: true,
        hasBeenUsed: false,
        restrictions: {},
    },
    BROOMOPHONE: {
        id: "BROOMOPHONE",
        name: "Broomophone",
        description: `The 5th time you chord in an office, remove 3 unflagged ${flavorConstants.ENEMY_NAME}`,
        cost: 7,
        effect: { activatedRemoveBomb: 3 },
        icon: 51,
        permanent: true,
        singleton: false,
        activated: true,
        hasBeenUsed: false,
        restrictions: {},
    },
    BROOMDRUM: {
        id: "BROOMDRUM",
        name: "DroomBrum",
        description: `The 4th time you consecutively chord in an ${flavorConstants.FIGHT_NAME}, +1 max hp only, once per ${flavorConstants.FIGHT_NAME}`,
        cost: 16,
        effect: { activatedGainMaxhp: 1 },
        icon: 44,
        permanent: true,
        singleton: false,
        activated: true,
        hasBeenUsed: false,
        restrictions: {},
    },
    INITIAL_CLICK_EXPAND_ONE: {
        id: "INITIAL_CLICK_EXPAND_ONE",
        name: "First Sweep Expander",
        description: "Enlarges your first sweep size by one",
        cost: 13,
        effect: { initialClickEnlarge: 1 },
        icon: 15,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    INITIAL_CLICK_CORNERS_ONE: {
        id: "INITIAL_CLICK_CORNERS_ONE",
        name: "First Sweep Corner Brush",
        description: "Enlarges your first sweep size to include all 4 corners",
        cost: 13,
        effect: { initialClickCorners: 1 },
        icon: 12,
        permanent: true,
        singleton: true,
        activated: false,
        restrictions: {},
    },
    GRID_SHRINK_ONE: {
        id: "GRID_SHRINK_ONE",
        name: "Paint the Walls",
        description: "Shrink Office grids by 1 height and width",
        cost: 0,
        effect: { fightGridExpand: -1 },
        icon: 28,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: {},
    },
    OVERWORLD_MAP_REVEAL: {
        id: "OVERWORLD_MAP_REVEAL",
        name: "Lobby Maps",
        description: "Reveals entire Lobby Map",
        cost: 7,
        effect: {},
        icon: 35,
        permanent: true,
        singleton: true,
        activated: false,
        restrictions: {},
    },
    TENTACLE_SLOW: {
        id: "TENTACLE_SLOW",
        name: "Tentacle Musk",
        description: "Slows the spread of Tentacles",
        cost: 7,
        effect: { tentacleIncrement: 10 },
        icon: 38,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: { advancedMechanics: "fightCanHaveTentacles" },
    },
    TRUSTED_NUMBER_THREE: {
        id: "TRUSTED_NUMBER_THREE",
        name: "Trusty 3s",
        description: "3s cannot lie",
        cost: 21,
        effect: { trustedNumber: 3 },
        icon: 39,
        permanent: true,
        singleton: true,
        activated: false,
        restrictions: { advancedMechanics: "fightCanHaveLyingTiles" },
    },
    UMBRELLA_USES_TWO: {
        id: "UMBRELLA_USES_TWO",
        name: "Extra Towels",
        description: "Adds 2 uses to towel key",
        cost: 7,
        effect: { umbrellaUses: 2 },
        icon: 21,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: { key: "UMBRELLA" },
    },
    CEMENT_USES_TWO: {
        id: "CEMENT_USES_TWO",
        name: "Extra Cement",
        description: "Adds 2 uses to cement key",
        cost: 15,
        effect: { blockUses: 2 },
        icon: 23,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: { key: "BLOCK" },
    },
    CEMENT_SIZE_TWO: {
        id: "CEMENT_USES_TWO",
        name: "Extra Cement",
        description: "Adds 1 height and width to the Cement Key",
        cost: 18,
        effect: { blockSize: 1 },
        icon: 36,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: { key: "BLOCK" },
    },
    TOWER_USES_TWO: {
        id: "TOWER_USES_TWO",
        name: "Extra Stepstools",
        description: "Adds 2 uses to stepstool key",
        cost: 10,
        effect: { towerUses: 2 },
        icon: 22,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: { key: "TOWER" },
    },
    REMOVE_TRASH_TILE_TWO: {
        id: "REMOVE_TRASH_TILE_TWO",
        name: "Big Trash Can",
        description: "Adds 2 uses to Remove Trash Key",
        cost: 9,
        effect: { trashTileRemoveUses: 2 },
        icon: 34,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: { key: "REMOVE_TRASH" },
    },
    REMOVE_TRASH_REWARD_THREE: {
        id: "REMOVE_TRASH_REWARD_THREE",
        name: "Bottle Collection",
        description: "Whenever you remove a trash tile, gain $2",
        cost: 10,
        effect: { trashTileRemoveReward: 2 },
        icon: 14,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: { key: "REMOVE_TRASH" },
    },
};

export const SPECIAL_ITEMS: { [key: string]: shopItemType } = {
    NEST_EGG: {
        id: "NEST_EGG",
        name: "Nest Egg",
        description: "Open to gain random items. ",
        cost: 0,
        effect: { nest_egg: 1 },
        icon: 11,
        permanent: true,
        singleton: true,
        activated: false,
        restrictions: { character: "CHAR_TWO" },
    },
    LUCKY_COIN: {
        id: "LUCKY_COIN",
        name: "Lucky Coin",
        description: "Makes life a little easier",
        cost: 10,
        effect: {},
        icon: 10,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: { event: "LUCKY_COIN" },
    },
    UNLUCKY_COIN: {
        id: "UNLUCKY_COIN",
        name: "Rusty Coin",
        description: "Makes life a little tougher",
        cost: 0,
        effect: {},
        icon: 57,
        permanent: true,
        singleton: false,
        activated: false,
        restrictions: { event: "LUCKY_COIN" },
    },
};

// export const testingItems: shopItemType[] = [
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
//     {
//         id: "SHOP_ITEMS_ADD_3",
//         name: "Bigger Vending Machine",
//         description: "Adds 3 more items to future vending machines",
//         cost: 4,
//         effect: { shopItemsAdd: 3 },
//         icon: "🥤",
//         permanent: true,
//         singleton: true,
//     },
// ];

export type shopItemType = {
    id: string;
    name: string;
    description: string;
    permanent: boolean;
    singleton: boolean;
    cost: number;
    effect: any;
    icon: number;
    activated: boolean;
    hasBeenUsed?: boolean;
    restrictions: { [key: string]: any };
};

export const SHOP_CONSTANTS = {
    SHOP_TILE_WIDTH: 192,
    SHOP_TILE_HEIGHT: 154,
    SHOP_TILE_OFFSET_X: 64,
    SHOP_TILE_NAME_OFFSET_Y: 0,
    SHOP_TILE_COST_OFFSET_Y: 24,
    SHOP_TILE_DESC_OFFSET_Y: 24,
    SHOP_TILE_FONT_SIZE: 32,
    NUM_PAD_TILE_WIDTH: 68,
    NUM_PAD_TILE_HEIGHT: 68,
};
